### ISSUE TITLE
compilationerror with pio

### ISSUE THREAD

**Issue by Rothammel** [cyrusbuilt/ArduinoCrashMonitor#1]
Processing uno (platform: atmelavr; board: uno; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/uno.html
PLATFORM: Atmel AVR > Arduino Uno
HARDWARE: ATMEGA328P 16MHz 2KB RAM (31.50KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <OneWire> 2.3.4
|-- <PubSubClient> 2.7
|-- <Time> 1.5
|-- <ArduinoCrashMonitor> 1.2.0
|-- <Ethernet> 1.1.2
|   |-- <SPI> 1.0
|-- <SPI> 1.0
Compiling .pioenvs\uno\src\Frischwasserstation_1_Trinkwasser.cpp.o
Compiling .pioenvs\uno\lib888\Ethernet\Dns.cpp.o
src\Frischwasserstation_1_Trinkwasser.cpp:17:33: fatal error: ArduinoCrashMonitor.h: No such file or directory

*****************************************************************************
* Looking for ArduinoCrashMonitor.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ArduinoCrashMonitor.h"
* Web  > https://platformio.org/lib/search?query=header:ArduinoCrashMonitor.h
*
*****************************************************************************

compilation terminated.
*** [.pioenvs\uno\src\Frischwasserstation_1_Trinkwasser.cpp.o] Error 1

**Comment by cyrusbuilt** [comment]
Without knowing how you are calling into the library, I cannot replicate the issue.  I have other projects that depend on ArduinoCrashMonitor (installed via PIO) that compile correctly.  It should be included using the following syntax:

```
#include "ArduinoCrashMonitor.h"
```

versus

```
#include <ArduinoCrashMonitor.h>
```

Could you provide some more detail?

**Comment by cyrusbuilt** [comment]
Closing due to lack of response
