### ISSUE TITLE
Possible to make compatible with SAM based controllers?

### ISSUE THREAD

**Issue by caiello3** [cyrusbuilt/ArduinoCrashMonitor#3]
Hello,

I have been working on a project based on the Arduino MKR NB 1500, which has a SAM based controller. It keeps crashing but I can't figure out why (I've had it looked over by experienced devs with no obvious issue in the code) so I was hoping to use this. I know this is for AVR based controllers only, but what I'm wondering is if it is possible to make this compatible with SAM based controllers? I am relatively new to coding, so I'm not sure if the dependency is only on the avr/wdt.h or if it is deeper rooted than that. From what I've read there is a WDT for the MKR NB 1500's SAM D21 controller. Sorry for the ignorance here.

Thanks!

**Comment by cyrusbuilt** [comment]
I'm certain it probably is possible. I already made another library called
ESPCrashMonitor that works with the ESP32 and ESP8266 chips. I'll look into
the SAM stuff. I dont have a SAM-based board at the moment, so I won't be
able to test it.

**Comment by caiello3** [comment]
that would be awesome if you made a SAM-compatible version. Is that something you'd be interested/able to do anytime soon? I would be willing to mail you one of my SAM-based boards (MKR NB 1500) to test, assuming you'd send it back.

**Comment by cyrusbuilt** [comment]
I've already started working on it.  I've figured out how to enable/disable
the watchdog function on the D21 which is a little tricky because it
requires synchronizing on some state flags, but still working out how to
feed the watchdog and if possible also implement some type of crash
logging/reporting like in the other 2 libraries.  As for the hardware, that
may not be be necessary if you would be willing to beta test the library
for me.

**Comment by caiello3** [comment]
Hey Chris,

You rock for jumping into this so quickly! I may need some guidance on how
to properly implement/ test it, as I'm pretty new to this, but I'm
certainly more than happy to help.

Thanks!
Chris

**Comment by cyrusbuilt** [comment]
I got the core library code and an example written and it compiles.
Supports SAM D21 and D51 variants.  I gotta write some support files in
order to package it up as a library and run it through CI, but I should be
able to have it completed sometime Tuesday (I think).

**Comment by caiello3** [comment]
Awesome! I'll be on the lookout and ready to test when it's ready.

**Comment by cyrusbuilt** [comment]
It's not done, but keep an eye on this repo:
[https://github.com/cyrusbuilt/SAMCrashMonitor](https://github.com/cyrusbuilt/SAMCrashMonitor)

So far it builds fine in CI:
[https://travis-ci.com/cyrusbuilt/SAMCrashMonitor/builds/146275020](https://travis-ci.com/cyrusbuilt/SAMCrashMonitor/builds/146275020)

**Comment by cyrusbuilt** [comment]
Ok its ready for testing. Download the source as zip and extract it to the 'lib' folder in your PlatformIO project, or if you are using the Arduino IDE following whatever instructions for manually installing libraries. Once installed, you can include it in your sketch with:

#include "SAMCrashMonitor.h"

And then in your setup() function add:

SAMCrashMonitor.dump(Serial);
int timeoutActual = SAMCrashMonitor.enableWatchdog(<timeout alue in milliseonds>);
Serial.print("Watchdog enabled with timeout value: ");
Serial.println(timeoutActual);

and in your loop() function add:
SAMCrashMonitor.iAmAlive();

If you want to force a hang and test the reset, add the following either in your loop() or setup() after enabling the watchdog:

while(true) { ;; }

Let me know how it behaves.  Assuming it works as expected, I'll release the library to the PlatformIO library registry so it can be installed with 'pio lib install SAMCrashMonitor'.

**Comment by caiello3** [comment]
I will test tonight and let you know how it goes. If I encounter any issues I'll document them in the SAMCrashMonitor repo.
